---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-es-master-0
  namespace: es
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-es-data-0
  namespace: es
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-es-client-0
  namespace: es
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: es
spec:
  version: 7.6.2
  http:
    service:
      spec:
        type: NodePort
  transport:
    service:
      spec:
        type: NodePort
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: es-master-0
  - name: data
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: es-data-0
  - name: client
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: es-data-0
