apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: es
spec:
  version: 7.6.2
  count: 1
  http:
    service:
      spec:
        type: NodePort
  elasticsearchRef:
    name: elasticsearch
    namespace: es
