apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: es
spec:
  version: 7.6.2
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
  elasticsearchRef:
    name: elasticsearch
    namespace: es
  podTemplate:  
    spec:
      containers:
      - name: kibana
        #env:
        #  - name: XPACK_SECURITY_ENABLED
        #    value: "false"
