kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-data
  namespace: es
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
