---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: es
spec:
  version: 7.6.2
  http:
    tls:
     selfSignedCertificate:
       disabled: true
    service:
      spec:
        type: LoadBalancer
  transport:
    service:
      spec:
        type: NodePort
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
      xpack.security.enabled: false
      xpack.security.authc:
         anonymous:
           username: anonymous
           roles: superuser
           authz_exception: false
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodename
                  operator: In
                  values:
                  - linux
        volumes:
        - name: es-master-0
  - name: data
    count: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: es-data-0
  - name: client
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: es-data-0
