apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
  namespace: es
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
